In [1]:
import numpy as np

In [3]:
xArray = np.ones((3,4))

In [4]:
xArray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
from scipy import linalg

In [7]:
arr = np.array([[1,2],[3,4]])
linalg.det(arr)

-2.0

### ndarray

In [8]:
# create ndarray

In [9]:
x1 = np.array([1,2,3])

In [10]:
x1

array([1, 2, 3])

In [11]:
x1.shape

(3,)

In [12]:
x2 = np.array([[1,2,3],[4,5,6]])
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
x3 = np.zeros((2,3))
x3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
x4 = np.ones((2,3))
x4

array([[1., 1., 1.],
       [1., 1., 1.]])

### most useful

In [15]:
x5 = np.full((3,4),np.pi)

In [16]:
x5

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [17]:
x1.dtype

dtype('int64')

In [18]:
x5.dtype

dtype('float64')

#### assign the type

In [19]:
np.array([1,2,3],dtype = np.int32)

array([1, 2, 3], dtype=int32)

In [20]:
x4.astype(np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.full_like(x4,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
# difference

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3) #more useful

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.arange(1,5,0.5) # 给定步长

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [29]:
np.linspace(1,2,7,endpoint = False)  # 给定取样个数

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286])

In [30]:
np.random.random((2,2))

array([[0.42872506, 0.455472  ],
       [0.52875261, 0.52197863]])

In [31]:
np.fromfunction(lambda i,j : (i+1)*(j+1),(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

### slice

In [32]:
x2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
print(x2[:,[0,1]])

[[1 2]
 [4 5]]


In [38]:
aArray = np.arange(1,101)
bArray = aArray[aArray<=50]
bArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [39]:
bool_a = aArray<=20
bool_a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [40]:
aArray[aArray%2==0]=0

In [41]:
aArray

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49,  0, 51,
        0, 53,  0, 55,  0, 57,  0, 59,  0, 61,  0, 63,  0, 65,  0, 67,  0,
       69,  0, 71,  0, 73,  0, 75,  0, 77,  0, 79,  0, 81,  0, 83,  0, 85,
        0, 87,  0, 89,  0, 91,  0, 93,  0, 95,  0, 97,  0, 99,  0])

In [43]:
y = np.random.random((3,3))
np.where(y>=0.5 ,1 ,-1)

array([[-1,  1, -1],
       [-1,  1,  1],
       [-1, -1,  1]])

In [44]:
y

array([[0.15159947, 0.56932374, 0.01625145],
       [0.19465411, 0.88092162, 0.85938572],
       [0.20187842, 0.45307446, 0.85956761]])

In [45]:
a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
print(b)
np.where(y>=0.5,a,b)

[1 2 3]
[4 5 6]


array([[4, 2, 6],
       [4, 2, 3],
       [4, 5, 3]])

In [46]:
x= np.arange(1,51)
x.reshape((5,10)) #x not change

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [47]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [48]:
x.resize(5,10) #change x

In [49]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### 堆叠

In [55]:
aArray = np.array([1,2,3])
bArray = np.array([4,5,6])
np.vstack((aArray,bArray))

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.hstack((aArray,bArray))

array([1, 2, 3, 4, 5, 6])

In [57]:
aArray*bArray

array([ 4, 10, 18])

In [58]:
y1 = np.matrix([[1,2],[3,4]])
y2 = np.matrix([[5,6],[7,8]])

In [59]:
y1

matrix([[1, 2],
        [3, 4]])

In [61]:
y2

matrix([[5, 6],
        [7, 8]])

In [60]:
y1*y2

matrix([[19, 22],
        [43, 50]])

In [62]:
np.dot(aArray,bArray)

32